// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (window.simsketch == null) {
    window.simsketch = {};
  }

  window.simsketch.EmptyTool = (function(_super) {
    __extends(EmptyTool, _super);

    function EmptyTool() {
      EmptyTool.__super__.constructor.apply(this, arguments);
    }

    return EmptyTool;

  })(paper.Tool);

}).call(this);

/*
//@ sourceMappingURL=EmptyTool.map
*/
