// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  window.SimSketchModes = {
    empty: 0,
    drawing: 1,
    erasing: 2,
    grouping: 3,
    playing: 4
  };

}).call(this);

/*
//@ sourceMappingURL=SimSketchModes.map
*/
